version: '3.9'

services:
  java_app:
    container_name: tecnical-app
    image: pee-tecnical-app:1.0.0
    build: .
    ports:
      - 8080:8080
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: oscarfonts/h2
    ports:
      - "9092:9092"
    environment:
      - H2_OPTIONS=-ifNotExists
      - H2_TCP_PORT=9092